from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.api import deps
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

router = APIRouter()

@router.get("/productivity-report")
def generate_productivity_report(
    db: Session = Depends(deps.get_db),
    current_user = Depends(deps.get_current_active_user),
):
    # Create an in-memory byte stream for the PDF
    buffer = io.BytesIO()
    
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Draw things on the PDF
    p.setFont("Helvetica-Bold", 20)
    p.drawString(50, height - 50, "Productivity Platform - Admin Report")
    
    p.setFont("Helvetica", 12)
    p.drawString(50, height - 100, f"Generated by: {current_user.email}")
    p.drawString(50, height - 120, "Total Employees: 124")
    p.drawString(50, height - 140, "Active Tasks: 45")
    p.drawString(50, height - 160, "Completed Tasks: 312")
    p.drawString(50, height - 180, "Average Productivity Score: 82.4/100")
    
    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # File object needs to be seeked to the beginning
    buffer.seek(0)
    
    headers = {
        'Content-Disposition': 'attachment; filename="productivity_report.pdf"'
    }
    
    return StreamingResponse(buffer, media_type="application/pdf", headers=headers)
